### ISSUE TITLE
How would you apply a backend (like with i18next-fs-backend)?

### ISSUE THREAD

**Issue by chadacious** [eelkevdbos/elysia-i18next#7]
Wondering the proper approach to implement am i18next backend with this plugin (like  i18next-fs-backend)

**Comment by eelkevdbos** [comment]
You simply create the instance like you would normally do (https://react.i18next.com/latest/i18next-instance), and then supply that instance to the middleware:

```ts
// i18n.ts
import i18n from 'i18next';
import Backend from 'i18next-fs-backend';

i18n
  .use(Backend)
  .init({
    fallbackLng: 'en',
    debug: true,
  });

export default i18n;
```

```ts
// app.ts
import { Elysia } from "elysia";
import { i18next } from "elysia-i18next";
import i18n from "./i18n.ts" // your i18n configured instance

new Elysia()
  .use(i18next({instance: i18n}))
  .get("/", ...)
```

Are you running into unexpected issues?

**Comment by chadacious** [comment]
Oh yeah! That works perfectly. Sorry, I'm a little new to Elysia and still wrapping my head around it. Thanks!
